version: "3.8"

services:
  captioni-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    environment:
      REDIS_URL: ${REDIS_URL}
      R2_ENDPOINT: ${R2_ENDPOINT}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-4}
      NODE_ENV: production
    volumes:
      - /tmp:/tmp
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
